config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "user/registrations",
    omniauth_callbacks: "callbacks"
  }
  resources :rides, only: [:index, :show] do
    member do
      get :contact
    end
  end
  scope module: :rides do
    resources :rides, only: [] do
      resources :requests, only: [:index, :show, :create]
    end
  end
  namespace :account do
    resource :validation, only: [:edit, :update]
    resources :rides
  end

  resources :webhooks, only: [:index, :create]

  root 'rides#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/mentions-legales', to: 'pages#legal_mentions'
end

app/models/ride.rb
# == Schema Information
#
# Table name: rides
#
#  id           :bigint(8)        not null, primary key
#  owner_id     :bigint(8)
#  origin       :string
#  destination  :string
#  departure_at :datetime
#  capacity     :integer
#  price        :decimal(, )
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Ride < ApplicationRecord
  belongs_to :owner, class_name: 'User'

  validates :origin, :destination, :departure_at, :capacity, :price, presence: true

  validates :price, numericality: { greater_than_or_equal_to: 0 }

  validates :capacity, numericality: { greater_than_or_equal_to: 1, only_integer: true }

  validate :departure_at_cannot_be_in_the_past, on: :create
  validate :departure_at_cannot_be_in_the_past, on: :update, if: :departure_at_changed?

  def departure_at_cannot_be_in_the_past
    if departure_at.present? && departure_at < Time.now
      errors.add(:departure_at, :cannot_be_in_the_past)
    end
  end
end

app/controllers/account/rides_controller.rb
class Account::RidesController < ApplicationController
  before_action :set_ride, only: [:show, :edit, :update, :destroy]

  # GET /account/rides
  # GET /account/rides.json
  def index
    @rides = current_user.rides
  end

  # GET /account/rides/1
  # GET /account/rides/1.json
  def show
  end

  # GET /account/rides/new
  def new
    @ride = current_user.rides.new
  end

  # GET /account/rides/1/edit
  def edit
  end

  # POST /account/rides
  # POST /account/rides.json
  def create
    @ride = current_user.rides.new(ride_params)

    respond_to do |format|
      if @ride.save
        format.html { redirect_to account_ride_path(@ride), notice: 'Ride was successfully created.' }
        format.json { render :show, status: :created, location: account_ride_path(@ride) }
      else
        format.html { render :new }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /account/rides/1
  # PATCH/PUT /account/rides/1.json
  def update
    respond_to do |format|
      if @ride.update(ride_params)
        format.html { redirect_to account_ride_path(@ride), notice: 'Ride was successfully updated.' }
        format.json { render :show, status: :ok, location: account_ride_path(@ride) }
      else
        format.html { render :edit }
        format.json { render json: @ride.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /account/rides/1
  # DELETE /account/rides/1.json
  def destroy
    @ride.destroy
    respond_to do |format|
      format.html { redirect_to account_rides_url, notice: 'Ride was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_ride
    @ride = current_user.rides.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ride_params
    params.require(:ride).permit(:owner_id, :origin, :destination, :departure_at, :capacity, :price)
  end
end

app/controllers/rides/requests_controller.rb
class Rides::RequestsController < ApplicationController
  def create
    @ride = Ride.find params[:ride_id]

    @request = current_user.requests.new(request_params)
    @request.ride_id = @ride.id

    if @request.save
      ApplicationMailer.new_request(@request.id).deliver_now
      redirect_to root_path, notice: t(".success")
    else
      redirect_to root_path, alert: t(".error", error: @request.errors.full_messages.join(", "))
    end
  end

  private

  def request_params
    params.require(:request).permit(:number_of_passengers, :original_message)
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  skip_before_action :authenticate_user!, except: [:contact]
  before_action :set_ride, only: [:show, :contact]

  # GET /rides
  # GET /rides.json
  def index
    @rides = Ride.all
  end

  # GET /rides/1
  # GET /rides/1.json
  def show
  end

  # GET /rides/1/contact
  def contact
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_ride
    @ride = Ride.find(params[:id])
  end
end

app/helpers/rides/requests_helper.rb
module Rides::RequestsHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/views/rides/_form.html.erb
<%= form_with(model: ride, local: true) do |form| %>
  <% if ride.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ride.errors.count, "error") %> prohibited this ride from being saved:</h2>

      <ul>
      <% ride.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :origin %>
    <%= form.text_field :origin, required: true, class: "form-control google-place-autocomplete" %>
  </div>

  <div class="form-group">
    <%= form.label :destination %>
    <%= form.text_field :destination, required: true, class: "form-control google-place-autocomplete" %>
  </div>

  <div class="form-group">
    <%= form.label :departure_at %>
    <%= form.text_field :departure_at, required: true, class: "form-control datetimepicker" %>
  </div>

  <div class="form-group">
    <%= form.label :capacity %>
    <%= form.text_field :capacity, required: true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, required: true, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Create Ride", class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/rides/contact.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <h2><%= t(".ride_request") %></h2>
    <hr />
    <%= form_for Request.new, url: ride_requests_path(ride_id: @ride.id) do |f| %>

      <div class="form-group">
        <%= f.label :number_of_passengers %><br />
        <%= f.number_field :number_of_passengers, autofocus: true, required: true, min: 1, class: "form-control" %>
      </div>

       <div class="form-group">
        <%= f.label :original_message %><br />
        <%= f.text_area :original_message, required: true, pattern: ".{10,}", title: "10 caracters minimum", class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit t("defaults.send"), class: "btn btn-outline-primary" %>
      </div>
    <% end %>

  </div>
</div>

app/views/rides/index.html.erb
<% content_for(:page_title) do %>
  <%= Ride.model_name.human(count: @rides.count) %>
<% end %>

<h1><%= @rides.count%> <%= Ride.model_name.human(count: @rides.count) %></h1>

<br />

<table class="table">
  <thead>
    <tr>
      <th><%= Ride.human_attribute_name(:owner) %></th>
      <th><%= Ride.human_attribute_name(:origin) %></th>
      <th><%= Ride.human_attribute_name(:destination) %></th>
      <th><%= Ride.human_attribute_name(:departure_at) %></th>
      <th><%= Ride.human_attribute_name(:capacity) %></th>
      <th><%= Ride.human_attribute_name(:price) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <div class="container">
    <tbody>
      <% @rides.each do |ride| %>
        <tr>
          <td><%= ride.owner.first_name %> <%= ride.owner.last_name %></td>
          <td><%= ride.origin %></td>
          <td><%= ride.destination %></td>
          <td><%= ride.departure_at.strftime("%d/%m/%Y - %H:%M") %></td>
          <td><%= ride.capacity %></td>
          <td><%= number_to_currency(ride.price, unit: "€", separator: ",", delimiter: ".", format: "%n %u") %></td>
          <td><%= link_to t('.show'), ride %></td>
        </tr>
      <% end %>
    </tbody>
  </div>
</table>

<br>

<%= link_to t('defaults.new', resource: Ride.model_name.human), new_account_ride_path %>

app/views/rides/show.html.erb
<% content_for(:page_title) do %>
  <%= Ride.model_name.human %> :
  <%= @ride.origin %> -> <%= @ride.destination %>
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <strong><%= Ride.human_attribute_name(:owner) %> :</strong>
  <%= @ride.owner.first_name %>
  <%= @ride.owner.last_name %>
</p>

<p>
  <strong><%= Ride.human_attribute_name(:origin) %> :</strong>
  <%= @ride.origin %>
</p>

<p>
  <strong><%= Ride.human_attribute_name(:destination) %> :</strong>
  <%= @ride.destination %>
</p>

<p>
  <strong><%= Ride.human_attribute_name(:departure_at) %> :</strong>
  <%= @ride.departure_at.strftime("%d/%m/%Y - %H:%M") %>
</p>

<p>
  <strong><%= Ride.human_attribute_name(:capacity) %> :</strong>
  <%= @ride.capacity %>
</p>

<p>
  <strong><%= Ride.human_attribute_name(:price) %> :</strong>
  <%= number_to_currency(@ride.price, unit: "€", separator: ",", delimiter: ".", format: "%n %u") %>
</p>

<br/>

<%= link_to t(".send_a_message", recipient: @ride.owner.first_name), contact_ride_path(@ride.id), class: "btn btn-call-to-action" %>

<br />

<%= link_to t('defaults.back'), rides_path %>