config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    registrations: "user/registrations",
    omniauth_callbacks: "callbacks"
  }
  resources :rides, only: [:index, :show] do
    member do
      get :contact
    end
  end
  scope module: :rides do
    resources :rides, only: [] do
      resources :requests, only: [:index, :show, :create]
    end
  end
  namespace :account do
    resource :validation, only: [:edit, :update]
    resources :rides
  end

  resources :webhooks, only: [:index, :create]

  root 'rides#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/mentions-legales', to: 'pages#legal_mentions'
end

app/views/layouts/_navbar.html.erb
<div class="website-menu-top app-nav-mobile-container">
  <nav class="websites-menu">
    <p class="app-contrast-color app-nav-mobile websites-menu-closeBar">
      <span class="fa fa-times"></span>
      Menu
    </p>
    <div class="theme-menu-wrapper">
      <ul class="app-contrast-color theme-menu">
        <li class="theme-menu-item app-menu-admin">
          <div class="app-menu-container">
            <%= link_to t('.all_rides'), rides_path %>
          </div>
        </li>

        <% if user_signed_in? %>
          <li class="theme-menu-item app-menu-admin">
            <div class="app-menu-container">
              <%= link_to t('.my_rides'), account_rides_path %>
            </div>
          </li>
        <% end %>

        <li class="theme-menu-item app-menu-admin">
          <div class="app-menu-container">
            <% if user_signed_in? %>
              <%= link_to t('devise.shared.links.sign_out'), destroy_user_session_path, method: :delete %>
            <% else %>
              <%= link_to t('devise.shared.links.sign_in'), new_user_session_path %>
            <% end %>
          </div>
        </li>

        <li class="theme-menu-item app-menu-admin app-contrast-color" data-id="5764251" data-orden="0">
          <div class="app-menu-container">
            <%= link_to t('.back_to_wedding_website'), "https://www.mariages.net/web/danietmanu/bienvenuebemvindo-1" %>
          </div>
        </li>
        <li class="theme-menu-item app-menu-admin app-contrast-color">
          <div class="app-menu-container">
            <div class="dropdown show">
              <% if I18n.locale == I18n.default_locale %>
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Français
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <%= link_to "Português", { locale: 'pt-BR' }, class: "dropdown-item" %>
                </div>
              <% else %>
                <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Português
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <%= link_to "Français", { locale: 'fr' }, class: "dropdown-item" %>
                </div>
              <% end %>
            </div>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_notice.html.erb
<% if notice.present? %>
  <div class="alert alert-warning alert-dismissible fade show text-center" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">
        &times;
      </span>
    </button>
  </div>
<% elsif alert.present? %>
  <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">
        &times;
      </span>
    </button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Covoiturage Mariage Dani e Manu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div id="app-offset-pusher" class="theme">
      <div id="app-content-load" class="app-contrast-color light-color">
        <div class="premium-verifying-layer app-website-limit-reached-layer"></div>
        <div id="app-nav-mobile-pointer" class="relative">
          <a id="menutoggle" class="app-nav-mobile" aria-hidden="true">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
          </a>

          <div class="theme-wrapper">
            <div class="relative app-spinner-container">
              <div class="app-spinner-container-fadeto theme-header app-theme-background drag-image-fixed">
                <p class="theme-header-decoration">
                  <span class="app-contrast-color theme-header-ribbon theme-header-custom-title">Carpooling</span>
                  <span class="app-contrast-color app-custom-font-name theme-header-custom-name light-color">Daniele e Emmanuel</span>
                  <small class="app-contrast-color theme-header-custom-title light-color">Covoiturage | Carpooling</small>
                  <% if @rides.present? %>
                    <span class="app-contrast-color theme-header-circle theme-header-custom-title">
                      <strong class="app-contrast-color theme-header-custom-title">
                        <%= @rides.count %>
                      </strong>
                      trajet(s)
                    </span>
                  <% end %>
                  </p>
                </div>
              </div>

              <%= render 'layouts/navbar' %>

              <%= render "layouts/notice" %>

              <div class="wrapper app-website-page-content" id="scrollMobile">
                <div class="pure-u-1 websites-section">
                  <ul class="" data-idpage="5764251">
                    <li>
                      <div class="theme-post app-website-render" data-id="784863" data-idpage="5764251">
                        <div class="text-center">
                          <h1 class="app-custom-font-title-primary theme-post-title">
                            <%= content_for(:page_title) || "Nós vamos casar !" %>
                          </h1>
                        </div>
                        <div class="theme-post">
                          <%= yield %>
                        </div>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
          <div class="app-contrast-color websites-footer light-color">
            <div class="wrapper">
              <p class="text-center">
                <%= link_to 'Mentions légales', mentions_legales_path %>
              </p>
              <br/>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>